cmake_minimum_required(VERSION 3.20)
project(cpp_base_course)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)  # для clangd в neovim

add_executable(l01_task01 lesson1/task1.cpp)
add_executable(l01_task02 lesson1/task2.cpp)
add_executable(l01_task03 lesson1/task3.cpp)
add_executable(l01_task04 lesson1/task4.cpp)
add_executable(l02_task01 lesson2/task1.cpp)
add_executable(l02_task02 lesson2/task2.cpp)
add_executable(l02_task03 lesson2/task3.cpp)
add_executable(l02_task04 lesson2/task4.cpp)
add_executable(l02_task05 lesson2/task5.cpp)
add_executable(l02_task06 lesson2/task6.cpp)
add_executable(l02_task07 lesson2/task7.cpp)
add_executable(l02_task08 lesson2/task8.cpp)
add_executable(l02_task09 lesson2/task9.cpp)
add_executable(l02_task10 lesson2/task10.cpp)
add_executable(l02_task11 lesson2/task11.cpp)
add_executable(l02_task12 lesson2/task12.cpp)
add_executable(l02_task13 lesson2/task13.cpp)
